platform :ios, '10.0'

use_frameworks!

target 'GGXAppleSpeech_Example' do
  pod 'GGXAppleSpeech', :path => '../'

  target 'GGXAppleSpeech_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
